# Generated by Django 4.1.5 on 2023-01-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
